name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 12.x
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm run test --ci --coverage

  release:
    needs: test
    name: Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Set Node.js 12.x
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x

      - name: Configure CI Git User
        run: |
          git config --global user.name 'TheUnderScorer'
          git config --global user.email 'przemyslawzydek@gmail.com'
          git remote set-url origin https://TheUnderScorer:$GITHUB_TOKEN@github.com/TheUnderScorer/js-utils
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout and pull branch
        run: git checkout "${GITHUB_REF:11}" && git pull

      - name: Install Dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Authenticate with Registry
        run: |
          echo "@theunderscorer/utils:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package
        run: npm run version && npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
